master:
  image: fav/spark-2.4
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: localhost
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8888:8080
  volumes:
    - ./data:/tmp/data

graphdb:
  image: neo4j:latest
  hostname: graphdb
  ports:
    - 7474:7474
    - 7687:7687
  environment:
    - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    - NEO4J_apoc_import_file_enabled=true
    - NEO4J_dbms_shell_enabled=true
  volumes:
    - ./plugins:/plugins
    - ./data:/data
    - ./import:/import



worker1:
  image: fav/spark-2.4
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker1
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 4
    SPARK_WORKER_MEMORY: 2g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  ports:
    - 8081:8081
  volumes:
    - ./data:/tmp/data

worker2:
  image: fav/spark-2.4
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker2
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 4
    SPARK_WORKER_MEMORY: 2g
    SPARK_WORKER_PORT: 8882
    SPARK_WORKER_WEBUI_PORT: 8082
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  ports:
    - 8082:8082
  volumes:
    - ./data:/tmp/data

